export const GET_PRODUCT = "GET_PRODUCT";
export const GET_PRODUCT_SUCCES = "GET_PRODUCT_SUCCES";
export const GET_PRODUCT_ERROR = "GET_PRODUCT_ERROR";
export const GET_DETAILS = "GET_DETAILS";
export const GET_DETAILS_SUCCES = "GET_DETAILS_SUCCES";
export const GET_DETAILS_ERROR = "GET_DETAILS_ERROR";